import { createStore } from "solid-js/store";

export const get_default_data = () => {
  return {
    "full name": "",
    designation: "",
    phone: "",
    address: "",
    "email address": "",
    "github username": "",
    profile: "",

    education: [
      { institution: "", qualification: "", time: "" },
    ],

    "work experience": [
      { company: "", position: "", time: "" },
    ],

    skills: [""],
    interests: [""],
    oss: [{ "project name": "", description: "", languages: "" }],
  };
};

export const get_demo_data = () => {
  return {
    "full name": "Aryan Maurya",
    designation: "Full Stack Developer",
    phone: "+91 95XXXXXXXX",
    "email address": "aaxxxxxxx@xxx.com",
    "github username": "aryan0-1maurya",
    profile:
      "I'm a FullStack Web+Appp+Game developer . I'm looking forward to get a junior web developer's position at a reputed corporation / startup and building user friendly & responsive interfaces with Reactjs.",

    education: [
      {
        institution: "Nehru XXXXX XXXXXXX",
        qualification: "High School",
        time: "2017-2019",
      },
      {
        institution: "Nehru XXXXXX XXXXXX",
        qualification: "intermediate (11-12th grade)",
        time: "2019-2021",
      },
      {
        institution: "XXXXX XXXXXX University",
        qualification: "BCA",
        time: "2021-2024",
      },
    ],

    "work experience": [
      {
        company: "AXXXXX XXXXXX",
        position: "Remote frontend react developer (freelancing)",
        time: "2022 Oct - 2023 Jan",
      },
    ],

    skills: [
      "html skill-icons:html",
      "css skill-icons:css",
      "javascript skill-icons:javascript",
      "typescript skill-icons:typescript",
      "react logos:react",
      "vue logos:vue",
      "flutter logos:flutter",
      "tailwind css logos:tailwindcss-icon",
      "unocss simple-icons:unocss",
      "solid JS logos:solidjs-icon",
    ],

    interests: [
      "Hacking file-icons:terminal",
      "tweaking neovim skill-icons:neovim-dark",
      "lua scripting file-icons:lua",
      "Ricing linux bi:palette2",
      "shell scripting file-icons:terminal",
    ],

    oss: [
      {
        "project name": "YYYYY",
        description:
          "A Neovim config framework with blazing fast startuptime & beautiful UI providing solid defaults coming with many lua plugins specifically written for it. NvChad currently has more than 13,900+ stars on github, it's the most popular neovim only distro.",
        languages: "lua ",
      },
      {
        "project name": "ABCCC",
        description:
          "Quick resume / cv builder for making beautiful resumes & supports exporting to high quality svgs & pdfs. This resume is generated by quickcv web app.",
        languages: "typescript, solidJs, unocss, vite",
      },
      {
        "project name": "XXXXX",
        description:
          "A user intractiv egui based evm voiting system for goof voting and fasted best secured encrypted your information.",
        languages: "C# , VBs , C-- & Solidity",
      },
      {
        "project name": "ZZZZZZ",
        description:
          "Minimal pomodoro timer & todolist creator web app to track progress of your productiveness.",
        languages: "javascript, solidJs, css ",
      },
    ],
  };
};

export const [store, setStore] = createStore(get_default_data());
